auctions/urls.py
from django.urls import path

from . import views

app_name = 'auctions'

urlpatterns = [
    path('', views.index, name='index'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('register/', views.register, name='register'),

    path('create/', views.createListing, name='createListing'),
    path('close/<int:listingId>', views.closeListing, name='closeListing'),
    path('delete/<int:listingId>', views.deleteListing, name='deleteListing'),

    path('listings/<int:listingId>', views.ListingPage.as_view(), name='listingPage'),
    path('categories/', views.categoriesPage, name='categories'),
    path('watchlist/', views.watchlistPage, name='watchlistPage'),
    path('watchlistToggle/<int:listingId>', views.watchlistToggle, name='watchlistToggle')
]

commerce/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("auctions.urls"))
]

auctions/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

USERNAME_LENGTH = 32

class User(AbstractUser):
    ''' Use the properties and methods of AbstractUser '''
    pass


class AuctionListing(models.Model):
    isClosed = models.BooleanField(default=False)
    title = models.CharField(max_length=64)
    description = models.CharField(max_length=120)
    currentPrice = models.DecimalField(max_digits=10, decimal_places=2)
    lastBidAuthor = models.CharField(max_length=USERNAME_LENGTH)
    imageUrl = models.CharField(max_length=1024, blank=True)
    createdAt = models.DateTimeField(auto_now_add=True)
    author = models.CharField(max_length=USERNAME_LENGTH)

    CATEGORY_VALUES = ('fashion', 'toys', 'electronics', 'home')
    CATEGORY_LABELS = ('Fashion', 'Toys', 'Electronics', 'Home')
    
    CATEGORY_CHOICES = list(zip( CATEGORY_VALUES, CATEGORY_LABELS))
    category = models.CharField(max_length=12, choices=CATEGORY_CHOICES, blank=True)

    def __str__(self):
        return f'{self.title}'


class WatchlistItem(models.Model):
    auction = models.ForeignKey(
        AuctionListing,
        on_delete=models.CASCADE,
        related_name='watchlistReference',
    )
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='watchlistItems')


class Comment(models.Model):
    content = models.CharField(max_length=1024)
    commentAuthor = models.CharField(max_length=USERNAME_LENGTH)
    
    auction = models.ForeignKey(
        AuctionListing,
        on_delete=models.CASCADE,
        blank=True,
        null=True,
        related_name='comments'
    )

    def __str__(self):
        return f'Content: {self.content}'


class Bid(models.Model):
    value = models.DecimalField(max_digits=10, decimal_places=2)
    bidAuthor = models.CharField(max_length=USERNAME_LENGTH)
    
    auction = models.ForeignKey(
        AuctionListing,
        on_delete=models.CASCADE, 
        related_name='bids'
    )

    def __str__(self):
        return f'Value: {self.value} Bid author: {self.bidAuthor}'

auctions/forms.py
from django import forms

class AddBidForm(forms.Form):
	newBidValue = forms.DecimalField(
		widget=forms.NumberInput(attrs={ 'class': 'form-control', 'placeholder': 'Bid...' }),
		label='Your bid goes here', 
		max_digits=10, 
		decimal_places=2, 
		min_value=0,
	)
	prefix = 'bidForm_pre'


class AddCommentForm(forms.Form):
	newCommentValue = forms.CharField(
		widget=forms.Textarea(attrs={ 
			'class': 'newComment', 
			'placeholder': 'Add a comment...', 
			'cols': '90', 
			'rows': '7' 
		}),
		label=False,
		max_length=1024,
	)
	prefix = 'commentForm_pre'

auctions/views.py
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse
from django.views import View

from django.db import IntegrityError

from .models import *


def index(request):
    if 'watchlist' not in request.session:
        request.session['watchlist'] = []
    
    return render(request, 'auctions/index.html', {
        'auctionListings': AuctionListing.objects.all()
    })


def login_view(request):
    if request.method == 'POST':
        from django.contrib.auth.models import User
        
        # Attempt to sign user in
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)

        # Check if authentication successful
        if user is not None:
            login(request, user)
            return HttpResponseRedirect(reverse('auctions:index'))
        else:
            return render(request, 'auctions/login.html', {
                'message': 'Invalid username and/or password.'
            })
    else:
        return render(request, 'auctions/login.html')


def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse('auctions:index'))


def register(request):
    if request.method == 'POST':
        username = request.POST['username']
        email = request.POST['email']

        # Ensure password matches confirmation
        password = request.POST['password']
        confirmation = request.POST['confirmation']
        if password != confirmation:
            return render(request, 'auctions/register.html', {
                'message': 'Passwords must match.'
            })

        # Attempt to create new user
        try:
            user = User.objects.create_user(username, email, password)
            user.save()
        except IntegrityError:
            return render(request, 'auctions/register.html', {
                'message': 'Username already taken.'
            })
        login(request, user)
        return HttpResponseRedirect(reverse('auctions:index'))
    else:
        return render(request, 'auctions/register.html')


def createListing(request):
    if request.method == 'POST':
        # try to create a new auction listing
        title = request.POST['title']
        description = request.POST['description']
        currentPrice = request.POST['initialPrice']
        author = request.user.username
        
        # validate the ones that are not required
        imageUrl = request.POST['imageUrl']
        if not imageUrl:
            imageUrl = ''
        
        category = request.POST['categories']
        if not category:
            category = ''

        try:
            auctionListing = AuctionListing.objects.create(
                title=title,
                description=description,
                currentPrice=currentPrice,
                imageUrl=imageUrl,
                author=author,
                category=category
            )
            auctionListing.save()
        except IntegrityError:
            return render(request, 'auctions/createListing.html', {
                # give category choices as context to the select
                'categoryChoices': AuctionListing.CATEGORY_CHOICES,
                'message': 'Something went wrong when trying to create a new auction listing... Try again'
            })
        else:
            return HttpResponseRedirect(reverse('auctions:index'))
    elif User.is_authenticated:
        return render(request, 'auctions/createListing.html', {
            # give category choices as context to the select
            'categoryChoices': AuctionListing.CATEGORY_CHOICES
        })


def closeListing(request, listingId):
    listing = AuctionListing.objects.get(pk=listingId)

    if listing.lastBidAuthor:
        try:
            winner = User.objects.get(username=listing.lastBidAuthor)
            listing.isClosed = True
            listing.save()
            
            try:
                # verify if the item is already inside the watchlist
                closedListing = winner.watchlistItems.get(auction_id=listing.id)
            except:
                closedListing = winner.watchlistItems.create(auction=listing, user=winner)
                closedListing.save()

            msg = f'The winner is {winner.username}, {listing} was closed!'
        except Exception as exc:
            msg = exc
    else:
        listing.delete()
        msg = f'There\'s no winner, the listing was deleted!'

    print(msg)

    return render(request, 'auctions/closeListing.html', { 'mensagem': msg })


def deleteListing(request, listingId):
    try:
        listing = AuctionListing.objects.get(pk=listingId)
        listing.delete()
        print('The auction listing was deleted')
    except Exception as exc:
        print(exc)
    
    return HttpResponseRedirect(reverse('auctions:watchlistPage'))


class ListingPage(View):
    from .forms import AddBidForm, AddCommentForm

    template_name = 'auctions/listingPage.html'

    def _getForm(self, request, formClass, prefix):
        data = request.POST if prefix in request.POST else None
        return formClass(data, prefix=prefix)

    def verifyItemInWatchlist(self, watchlist, listingId):
        for item in watchlist:
            if listingId == item.auction_id:
                return True
        return False

    def get(self, request, listingId):
        auctionListing = AuctionListing.objects.get(id=listingId)
        currentUser = request.user.username

        isInWatchlist = None

        if request.user.is_authenticated:
            isInWatchlist = self.verifyItemInWatchlist(request.user.watchlistItems.all(), listingId)

        return render(request, self.template_name, {
            'listing': auctionListing,
            'BidForm': self.AddBidForm(),
            'CommentForm': self.AddCommentForm(),
            'currentUser': currentUser,
            'listingIsInWatchlist': isInWatchlist
        })

    def post(self, request, listingId):
        auctionListing = AuctionListing.objects.get(id=listingId)

        BidForm = self._getForm(request, self.AddBidForm, prefix=self.AddBidForm.prefix)
        CommentForm = self._getForm(request, self.AddCommentForm, prefix=self.AddCommentForm.prefix)

        currentUser = request.user.username

        isInWatchlist = None

        if request.user.is_authenticated:
            isInWatchlist = self.verifyItemInWatchlist(request.user.watchlistItems.all(), listingId)

        additionalErrorMessage = ''

        if CommentForm.is_valid() and CommentForm.is_bound:
            # create a new comment
            newCommentContent = CommentForm.cleaned_data['newCommentValue']

            try:
                newComment = Comment.objects.create(
                    content=newCommentContent,
                    commentAuthor=currentUser,
                    auction=auctionListing
                )

                newComment.save()
                
                CommentForm = self.AddCommentForm()
            except Exception as err:
                print(err)
        elif BidForm.is_valid() and BidForm.is_bound:
            newBidContent = BidForm.cleaned_data['newBidValue']

            if newBidContent > auctionListing.currentPrice:
                # post new bid
                try:
                    newBid = Bid.objects.create(
                        value = newBidContent,
                        bidAuthor=currentUser,
                        auction=auctionListing
                    )
                    
                    auctionListing.currentPrice = newBid.value
                    auctionListing.lastBidAuthor = currentUser

                    auctionListing.save()
                    newBid.save()
                    
                    BidForm = self.AddBidForm()
                except Exception as err:
                    print(err)
            else:
                additionalErrorMessage = """
                    <ul class="errorlist">
                        <li><strong>The bid should be greater than the current price</strong></li>
                    </ul>
                """
        else:
            print('Something went wrong...')

        return render(request, self.template_name, {
            'listing': auctionListing,
            'BidForm': BidForm,
            'currentUser': currentUser,
            'CommentForm': CommentForm,
            'listingIsInWatchlist': isInWatchlist,
            'additionalErrorMessage': additionalErrorMessage
        })


def categoriesPage(request):
    filteredAuctionListings = []
    
    if request.method == 'POST':
        categoryChosen = request.POST['categories']

        filteredAuctionListings = AuctionListing.objects.filter(category=categoryChosen)

    categoryChoices = AuctionListing.CATEGORY_CHOICES
    
    return render(request, 'auctions/categories.html', {
        'categoryChoices': categoryChoices,
        'filteredAuctionListings': filteredAuctionListings
    })


def watchlistPage(request):
    watchlist = request.user.watchlistItems.all()
    
    return render(request, 'auctions/watchlist.html', { 'watchlist': watchlist })


def watchlistToggle(request, listingId):
    from django.core.exceptions import ObjectDoesNotExist
    
    watchlistItems = request.user.watchlistItems
    auction = AuctionListing.objects.get(pk=listingId)

    try:
        # if there's already a watchlist item corresponding to the
        # current listing
        item = watchlistItems.get(auction_id=listingId)
        item.delete()
    except ObjectDoesNotExist:
        try:
             newItem = watchlistItems.create(auction=auction, user=request.user)
             newItem.save()
        except Exception as err:
             print(err)
    finally:    
        return HttpResponseRedirect(reverse('auctions:watchlistPage'))

auctions/templates/auctions/categories.html
{% extends './layout.html' %}

{% load static %}


{% block title %}
	Categories
{% endblock %}


{% block body %}
	<div class="categoriesPage">
		<h2 class="title">Categories</h1>
	
		<form class="formChooseCategory" action="{% url 'auctions:categories' %}" method="post">
			{% csrf_token %}
			
			<label for="categories">Choose a category here:</label>
	
			<select required name="categories" id="categories" class="custom-select">
				<option value="" selected hidden>Categories...</option>
				{% for category in categoryChoices %}
					<!-- 0 == value; 1 == label -->
					<option value={{ category.0 }}>{{ category.1 }}</option>
				{% endfor %}
			</select>
			
			<button class="btn btn-primary" type="submit">Choose Category</button>
		</form>

		<ul class="auctionListings">
			{% for auction in filteredAuctionListings %}
				{% if not auction.isClosed %}
					<li class="auction">
						{% if auction.imageUrl %}
							<img class="auctionImg" src={{ auction.imageUrl }} alt={{ auction.title }}>
						{% else %}
							<img class="auctionImg" src="{% static 'auctions/Images/No_image_available.png' %}">
						{% endif %}
						
						<div class="textRelated">
							<a href="{% url 'auctions:listingPage' auction.id %}">
								<h3 class="auctionTitle">{{ auction.title }}</h3>
							</a>
							<strong>Price:</strong> ${{ auction.currentPrice }} <br>
							<p>{{ auction.description }}</p>
							<em>Created {{ auction.createdAt }}</em>
						</div>
					</li>
				{% endif %}
			{% endfor %}
		</ul>
	</div>
{% endblock %}

auctions/templates/auctions/closeListing.html
{% extends './layout.html' %}

{% block title %}
	Close Listing
{% endblock %}

{% block body %}
	<div class="closeListingPage">
		<h2 class="title">
			{{ mensagem }}
		</h2>
		<a href="{% url 'auctions:index' %}" class="btn btn-primary">Go to index</a>
	</div>
{% endblock %}

auctions/templates/auctions/createListing.html
{% extends './layout.html' %}

{% block title %}
	Create Listing
{% endblock %}


{% block body %}
	<h2>Create a listing</h2>
	<p>Enter the information for the form below to create the new auction listing</p>
	
	{% if message %}
		<strong>
			<em>{{ message }}</em>
		</strong>
	{% endif %}
	
	<form class="createListingForm" action="{% url 'auctions:createListing' %}" method="post">
		{% csrf_token %}

		<div class="form-group">
			<input 
				autofocus
				required
				type="text" 
				class="form-control" 
				name="title" 
				placeholder="Title"
			>
		</div>
		<div class="form-group">
			<input 
				required
				type="text" 
				class="form-control" 
				name="description" 
				placeholder="Description"
			>
		</div>
		<div class="form-group">
			<input 
				required
				type="number" 
				class="form-control" 
				name="initialPrice"
				min="0"
				step=".01"
				placeholder="Initial price"
			>
		</div>
		<div class="form-group">
			<input 
				type="url" 
				class="form-control" 
				name="imageUrl" 
				placeholder="Image URL"
			>
		</div>

		<div class="form-group">
			<label for="categories">Select the category:</label>
			
			<select class="custom-select" id="categories" name="categories">
				<optgroup>
					<option selected hidden value="">...</option>
					{% for category in categoryChoices %}
						<!-- category.0 == value, category.1 == label -->
						<option value={{ category.0 }}>{{ category.1 }}</option> 
					{% endfor %}
				</optgroup>
			</select>
		</div>

		<div class="buttonContainer">
			<input class="btn btn-primary" type="submit" title="Create Auction Listing">
		</div>
	</form>
{% endblock %}

auctions/templates/auctions/index.html
{% extends "auctions/layout.html" %}

{% load static %}

{% block body %}
    <h2>Active Listings</h2>

    <ul class="auctionListings">
        {% for auction in auctionListings %}
            {% if not auction.isClosed %}
                <li class="auction">
                    {% if auction.imageUrl %}
                        <img class="auctionImg" src={{ auction.imageUrl }} alt={{ auction.title }}>
                    {% else %}
                        <img class="auctionImg" src="{% static 'auctions/Images/No_image_available.png' %}">
                    {% endif %}
                    
                    <div class="textRelated">
                        <a href="{% url 'auctions:listingPage' auction.id %}">
                            <h3 class="auctionTitle">{{ auction.title }}</h3>
                        </a>
                        <strong>Price:</strong> ${{ auction.currentPrice }} <br>
                        <p>{{ auction.description }}</p>
                        <em>Created {{ auction.createdAt }}</em>
                    </div>
                </li>
            {% endif %}
        {% endfor %}
    </ul>
{% endblock %}

auctions/templates/auctions/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
	<head>
		<meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<title>{% block title %}Auctions{% endblock %}</title>
		<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
		<link href="{% static 'auctions/sass/styles.css' %}" rel="stylesheet">
		<link rel="icon" href="{% static 'auctions/Icons/favicon.ico' %}">
	</head>
	<body>
		<header class="header">
			<h1 id="appTitle">Auctions</h1>
			
			<ul class="nav">
				<li class="nav-item">
					<a class="nav-link" href="{% url 'auctions:index' %}">Active Listings</a>
				</li>

				<li class="nav-item">
					<a class="nav-link" href="{% url 'auctions:categories' %}">Categories</a>
				</li>

				{% if user.is_authenticated %}
					<li class="nav-item">
						<a class="nav-link" href="{% url 'auctions:watchlistPage' %}">
							Watchlist
							<div class="sizeOfWatchlist">
								{{ user.watchlistItems.all|length }}
							</div>
						</a>
					</li>
					<li class="nav-item">
						<a class="nav-link" href="{% url 'auctions:createListing' %}">Create Listing</a>
					</li>    
					<li class="nav-item">
						<a class="nav-link" href="{% url 'auctions:logout' %}">Log Out</a>
					</li>
				{% else %}
					<li class="nav-item">
						<a class="nav-link" href="{% url 'auctions:login' %}">Log In</a>
					</li>
					<li class="nav-item">
						<a class="nav-link" href="{% url 'auctions:register' %}">Register</a>
					</li>
				{% endif %}
			</ul>
			
			<div class="userStatus">
				{% if user.is_authenticated %}
					Signed in as <strong>{{ user.username }}</strong>.
				{% else %}
					Not signed in.
				{% endif %}
			</div>
		</header>
		
		<hr>
		
		<div class="container-fluid">
			{% block body %}
			{% endblock %}
		</div>
	</body>
</html>

auctions/templates/auctions/listingPage.html
{% extends './layout.html' %}

{% load static %}

{% block title %}
	{{ listing.title }}
{% endblock %}

{% block body %}
	<div class="listingPageContainer">
		<div class="columnsContainer">
			<div class="col1">
				<h2 class="title">Listing: {{ listing.title }}</h2>
	
				{% if user.is_authenticated and not listing.isClosed %}
					<form action="{% url 'auctions:watchlistToggle' listing.id %}" method='post'>
						{% csrf_token %}
						<button type="submit" class="watchListButton">
							{% if listingIsInWatchlist %}
								Remove from WatchList
							{% else %}
								Add to Watchlist
							{% endif %}
						</button>
					</form>
				{% endif %}
				<br>
				
				{% if listing.imageUrl %}
					<img class="listingImg" src={{ listing.imageUrl }} alt={{ listing.title }}>
				{% else %}
					<img class="listingImg" src="{% static 'auctions/Images/No_image_available.png' %}">
				{% endif %}
	
				<p class="description">Description: {{ listing.description }}</p>
	
				<div class="listingPrice">
					<strong>Current price: ${{ listing.currentPrice }}</strong>
				</div>
	
				<h3 class="title">Details</h3>
				<ul>
					<li>Listed by: {{ listing.author }}</li>
					
					{% if listing.category %}
						<li>Category: {{ listing.category }}</li>
					{% else %}
						<li>Category: No Category</li>
					{% endif %}
				</ul>
			</div>
			
			<div class="col2">
				{% if not listing.isClosed %}
					<div class="bidArea">
						<h2 class="title">Bids</h2>
						<p>
							{{ listing.bids.all|length }} bids so far.
							
							{% if listing.lastBidAuthor %}
								{% if currentUser ==  listing.lastBidAuthor %}
									Your bid is the current bid.
								{% else %}
									Current bid is from {{ listing.lastBidAuthor }}
								{% endif %}
							{% endif %}
						</p>
						
						{% if user.is_authenticated %}
							<form action="{% url 'auctions:listingPage' listing.id %}" method="post">
								{% csrf_token %}
		
								<div class="form-group">
									{{ BidForm }}
								</div>
		
								{{ additionalErrorMessage|safe }}
				
								<div class="form-group">
									<button class="btn btn-primary" name="{{ BidForm.prefix }}" type="submit">
										Place bid
									</button>
								</div>
							</form>
						{% else %}
							To bid you need to stay <a href="{% url 'auctions:login' %}">logged in</a>
						{% endif %}
					</div>
				{% endif %}

				{% if currentUser == listing.author %}
					<div class="dangerZone">
						<h3 class="title">Danger zone</h3>
						<div class="closeBidConfirmation">
							<h5>Do you want to <strong>Close this auction listing?</strong></h5>
							<p>The last bidder will be the winner</p>
							<form action="{% url 'auctions:closeListing' listing.id %}" method="post">
								{% csrf_token %}

								<button type="submit" class="btn btn-outline-danger">Close bid</button>
							</form>
						</div>
					</div>
				{% elif listing.isClosed and user.username == listing.lastBidAuthor %}
					<div class="winnerArea">
						<h3 class="title">Congratulations, you're the winner!</h3>
						<div class="deleteBidConfirmation">
							<h5>Do you want to <strong>delete this auction listing?</strong></h5>
							<p>Since this bid is closed, you can decide to delete it from the database.</p>
							<form action="{% url 'auctions:deleteListing' listing.id %}" method="post">
								{% csrf_token %}

								<button type="submit" class="btn btn-outline-warning">Delete bid</button>
							</form>
						</div>
					</div>
				{% endif %}
			</div>
		</div>

		<hr>

		<div class="commentSection">
			<h3 class="commentSection__title">Comment Section</h3>
			
			{% for comment in listing.comments.all %}
				<div class="comment">
					<h4 class="comment__author">{{ comment.commentAuthor }} says</h4>
					<p class="comment__content">{{ comment.content }}</p>
				</div>
			{% empty %}
				<p class="no_comments_yet">No comments yet...</p>
			{% endfor %}

			{% if not listing.isClosed %}
				{% if user.is_authenticated %}
					<form action="{% url 'auctions:listingPage' listing.id %}" method="post">
						{% csrf_token %}
						
						{{ CommentForm }}

						<button class="btn btn-primary postComment" name="{{ CommentForm.prefix }}" type="submit">
							Post Comment
						</button>
					</form>
				{% else %}
					<em>
						To add a comment you need to stay <a href="{% url 'auctions:login' %}">logged in</a>
					</em>
				{% endif %}
			{% else %}
				<em>
					The comment section has been disabled.
				</em>
			{% endif %}
		</div>
	</div>
{% endblock %}

auctions/templates/auctions/login.html
{% extends "auctions/layout.html" %}

{% block body %}

    <h2>Login</h2>

    {% if message %}
        <div>{{ message }}</div>
    {% endif %}

    <form action="{% url 'auctions:login' %}" method="post">
        {% csrf_token %}
        <div class="form-group">
            <input autofocus required class="form-control" type="text" name="username" placeholder="Username" maxlength="32">
        </div>
        <div class="form-group">
            <input required class="form-control" type="password" name="password" placeholder="Password">
        </div>
        <input class="btn btn-primary" type="submit" value="Login">
    </form>

    Don't have an account? <a href="{% url 'auctions:register' %}">Register here.</a>

{% endblock %}

auctions/templates/auctions/register.html
{% extends "auctions/layout.html" %}

{% block body %}

    <h2>Register</h2>

    {% if message %}
        <div>{{ message }}</div>
    {% endif %}

    <form action="{% url 'auctions:register' %}" method="post">
        {% csrf_token %}
        <div class="form-group">
            <input class="form-control" autofocus type="text" name="username" placeholder="Username" maxlength="32">
        </div>
        <div class="form-group">
            <input class="form-control" type="email" name="email" placeholder="Email Address">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="password" placeholder="Password">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="confirmation" placeholder="Confirm Password">
        </div>
        <input class="btn btn-primary" type="submit" value="Register">
    </form>

    Already have an account? <a href="{% url 'auctions:login' %}">Log In here.</a>

{% endblock %}

auctions/templates/auctions/watchlist.html
{% extends './layout.html' %}

{% load static %}

{% block title %}
	Watchlist
{% endblock %}

{% block body %}
	<div class="watchlistPageContainer">
		<h2>Watchlist</h2>
		
		<ul class="auctionListings">
			{% for item in watchlist %}
				<li class="auction">
					{% if item.auction.imageUrl %}
						<img class="auctionImg" src={{ item.auction.imageUrl }} alt={{ item.auction.title }}>
					{% else %}
						<img class="auctionImg" src="{% static 'auctions/Images/No_image_available.png' %}">
					{% endif %}
					
					<div class="textRelated">
						<a href="{% url 'auctions:listingPage' item.auction.id %}">
							<h3 class="auctionTitle">{{ item.auction.title }}</h3>
						</a>

						{% if item.auction.isClosed %}
							<h3 class="alert alert-success">Closed. You Won!</h3>
						{% else %}
							<strong>Price:</strong> ${{ item.auction.currentPrice }} <br>
							<p>{{ item.auction.description }}</p>
							<em>Created {{ item.auction.createdAt }}</em>
						{% endif %}
					</div>
				</li>

				{% empty %}
					<li class="alert alert-primary">Your watchlist is empty, try adding some items</li>
			{% endfor %}
		</ul>
	</div>
{% endblock %}